module RGFPrecompConsumerTest
    # This module is used to test the following situation:
    # - A user has created a package (this module).
    # - The user's package consumes another package's API to build an RGF.
    # This kind of situation occurs, for example, when precompiling a package
    # that builds an ODEFunction generated by ModelingToolkit.

    using RGFPrecompTest

    # f_bad will NOT work, because it gets put into the RGFPrecompTest's cache
    f_bad = RGFPrecompTest.build_RGF(:((x,y)->x-y))

    # Instead, the user needs to set up a local RGF cache.
    # TODO: Perhaps this should be done automatically by @RuntimeGeneratedFunctions?
    using RuntimeGeneratedFunctions
    RuntimeGeneratedFunctions.init(@__MODULE__)

    # f_good will work, because it gets put into this module's cache
    f_good = RGFPrecompTest.build_RGF(:((x,y)->x-y), @__MODULE__)
end
